### ISSUE TITLE
After until pattern (test case: tmp_afteruntil01.cfr)

### ISSUE THREAD

**Issue by RaoMukkamala** [juodaspaulius/BehavioralClafer#2]
Checks
test case is ok ? Yes
Compiles ? Yes
De-sugars correctly ? No
Compiles in Alloy ? Not tested. 
Instances in alloy are ok? Not tetsed

```
   The constraint "[always c after d until e]" is wrongly de-sugared to
[G (some this . d U some this . e => G some this . c)]  

The above constraint should be de-sugared to 
"[ always (this .d && !this .e)  => (!this .e U (this .c && !this .e) )]"

Please refer to: http://patterns.projects.cis.ksu.edu/documentation/patterns/ltl.shtml
and also Slide 32 @: http://cs.gmu.edu/~pammann/619/ppt/SPECS-Patterns.pdf

One distinction between "between" scope and "after-until" scope is that "between: scope only requires the pattern to hold if a matching "e" exists after occurrence of "d".
In contrast, "after-until" requires that the pattern to hold after every "d" until "e" is occurred (in other words ).

The de-sugaring for the pattern "P exists after Q until R" from the property patterns page is:
[](Q & !R -> (!R U (P & !R)))
```

**Comment by juodaspaulius** [comment]
It was not parsing after-until pattern. It was because we also have `until` keyword (`U` alias).
So `[always c after d until e]` was parsing as `[always c after (d until e)]`.

After the fix this `[always c after d until e]` universality pattern constraint is desugared to:
`[G (some this . c0_d && no this . c0_e => some this . c0_c W some this . c0_e)]`

**Comment by RaoMukkamala** [comment]
Verified the desugaring of constraints and found that desugaring works perfectly and generates code matching to the property pattern correctly.

Constraint:&nbsp; `[always c after d until e ]`
Desugared constraint:&nbsp; `[G (some this . c0_d && no this . c0_e => some this . c0_c W some this . c0_e)]`
Property Pattern:&nbsp; `[ &nbsp; ](Q & !R -> (P W R))`

Constraint:&nbsp;`[never c after d until e ]`
Desugared constraint:&nbsp; `[G (some this . c0_d && no this . c0_e => no this . c0_c W some this . c0_e)]`
Property Pattern:&nbsp; `[ ](Q & !R -> (!P W R))`

Constraint:&nbsp;`[sometime c after d until e ]`
Desugared constraint:&nbsp;`[G (some this . c0_d && no this . c0_e => no this . c0_e U (some this . c0_c && no this . c0_e))]`
Property Pattern:&nbsp;`[ ](Q & !R -> (!R U (P & !R)))`
